//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fee_Refund_2021.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HSC_REFUND_2021Entities : DbContext
    {
        public HSC_REFUND_2021Entities()
            : base("name=HSC_REFUND_2021Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Tbl_CollegePaymentDetails> Tbl_CollegePaymentDetails { get; set; }
        public virtual DbSet<Tbl_Login> Tbl_Login { get; set; }
        public virtual DbSet<Tbl_Student> Tbl_Student { get; set; }
        public virtual DbSet<Tbl_Code_Master> Tbl_Code_Master { get; set; }
        public virtual DbSet<Tbl_CollegePaymentDetails_Bk> Tbl_CollegePaymentDetails_Bk { get; set; }
        public virtual DbSet<Tbl_Bank> Tbl_Bank { get; set; }
    }
}
