//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fee_Refund_2021.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Student
    {
        public int id { get; set; }
        public string schol_no { get; set; }
        public string seat_no { get; set; }
        public string name { get; set; }
        public string mname { get; set; }
        public string Status { get; set; }
        public string Fee_Paid { get; set; }
        public string Date { get; set; }
        public string Date_Time { get; set; }
    }
}
