//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fee_Refund_2021.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Bank
    {
        public int id { get; set; }
        public string clientCode { get; set; }
        public string van { get; set; }
        public string txnAmount { get; set; }
        public string payMode { get; set; }
        public string utrn { get; set; }
        public string remitterName { get; set; }
        public string remitterAccNo { get; set; }
        public string Ifsc { get; set; }
        public string remarks { get; set; }
        public string txnDate { get; set; }
    }
}
