//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fee_Refund_2021.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Login
    {
        public int id { get; set; }
        public string login_id { get; set; }
        public string password { get; set; }
        public Nullable<int> active { get; set; }
    }
}
