//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fee_Refund_2021.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_CollegePaymentDetails_Bk
    {
        public int id { get; set; }
        public string AccountHolderDetails { get; set; }
        public string AccountNumber { get; set; }
        public string IFSCCode { get; set; }
        public string BankName { get; set; }
        public string PrincipalName { get; set; }
        public string PrincipalMobile { get; set; }
        public string PrincipalEmail { get; set; }
        public string Index_No { get; set; }
        public string PrincipalSignature { get; set; }
        public Nullable<int> Active { get; set; }
        public string Date_time { get; set; }
    }
}
